import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PortfolioProvider } from "../context/context";
import { prefix } from "../config/config";

import { signIn, useSession, signOut } from "next-auth/react";


const Home: NextPage = () => {
	const { data, status } = useSession();
  return (
    
    <PortfolioProvider value={{ prefix }}>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>status: {status}</p>
        <p>{data?.user?.name}</p>
        {data?.user ? (
          <button type="button" onClick={() => signOut()}>
            Google Logout
          </button>
        ) : (
          <button type="button" onClick={async() => {
            await signIn();
          }}>
            Google Login
          </button>
        )}
      </main>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    </PortfolioProvider>
  )
}
export default Home